/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Emergency` | `/Emergency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Exercise` | `/Exercise`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Reminder` | `/Reminder`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Utilities` | `/Utilities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/movies/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Emergency` | `/Emergency`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Exercise` | `/Exercise`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Reminder` | `/Reminder`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Utilities` | `/Utilities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/movies/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Emergency${`?${string}` | `#${string}` | ''}` | `/Emergency${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Exercise${`?${string}` | `#${string}` | ''}` | `/Exercise${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Reminder${`?${string}` | `#${string}` | ''}` | `/Reminder${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Utilities${`?${string}` | `#${string}` | ''}` | `/Utilities${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Emergency` | `/Emergency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Exercise` | `/Exercise`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Reminder` | `/Reminder`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Utilities` | `/Utilities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/movies/${Router.SingleRoutePart<T>}` | { pathname: `/movies/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
